uz = {
    "servis": "🗂 Qaysi xizmatimizdan foydalanmoqchisiz?",
    "servis_btn1": "📂 Foydali ma’lumotlarni yuklab olish.",
    "servis_btn2": "🤖 AI Konsultantdan foydalanish.",
    "lang_change": "⚙️ Tilni o'zgartirish",
    "name_ask": "🧑🏻‍🎓 F. I. O. ingizni to'liq kiriting:",
    "passport_ask": "🪪 Passport seriya va raqamini kiriting:",
    "number_ask": "Telefon raqamingizni Raqamni yuborish 📞 tugmasi orqali yuboring \nyoki +998900000000 formatida kiriting: !",
    "extra_number": "📞 Qoshimcha telefon raqamingiz:",
    "age_ask": "🔢 Yoshingizni tanlang:",
    "ask_degree": "🏛 Qaysi bosqichga topshiryapsiz?",
    "ask_study": "🏢 Hozir qayerda o‘qiyapsiz yoki bitirgansiz?",
    "ask_region": "🏠 Qaysi viloyatda yashaysiz?",
    "ask_direction": "🧬 Qaysi yo‘nalishda o‘qishni xohlaysiz?",
    "ask_study_lang": "🔠 Ta’lim tili?",
    "ask_study_mode": "⏳ Ta’lim shakli?",
    "ask_aplic_type": "💎 Qabul jarayoni bo‘yicha qanday imkoniyat qidiryapsiz?",
    "ask_factor": "💼 Universitet tanlashda siz uchun eng muhim omil nima?",
    "ask_help": "👨‍👩‍👦‍ Sizga universitet qidirishda kim yordam beradi?",
    "ask_source": "🤖 Siz BOT haqida qayerdan eshitdingiz?",
    "ask_accept": "📝 Ma'lumotlaringiz to'g'ri ekanligini tasdiqlang:",
    "ask_right_pass": "⛓️‍💥 Passport malumotlarini xato kirittingiz.\nQaytadan kiriting.",
    "ask_name_again": "✍️ Ism faqat harfdan tashkil topishi mumkin. \nQaytadan kiriting.",
    "number_ask_again": "📲 Telefon raqamingizni to'g'ri kiriting!",
    "ask_number_again": "🚫 Kiritgan raqamingiz oldingisi bilan bir xil bo'la olmaydi!",
    "ask_sub": "🔊 Kanalga a’zo bo‘lish!",
    "ask_sub1": "📝 Siz hozir O’zbekistondagi eng katta abituriyentlar jamiyatiga qo‘shilmoqchisiz! \n✅ Universitetlar haqida eng so‘nggi ma’lumotlar \n✅ Grant va kontrakt imkoniyatlari bo‘yicha maslahatlar \n✅ Kirish imtihonlariga tayyorlanish uchun bepul resurslar \n✅ 24/7 AI Konsultant",
    "ask_fill_info": "✍️ Malumotlarni to'ldirish!",
    "see_info": "📄 Mening ma'lumotlarim.",
    "score": "💰 Mening ballarim",
    "didnt_sub":"❌ Siz hali ham kanalga a'zo bo‘lmadingiz!",
    "ask_fill":"❌ Bu xizmatdan foydalanish uchun oldin malumotlaringizni to'ldiring!",
    "file_button1":"🧾 Grant olish bo‘yicha maxsus qo‘llanma!",
    "file_button2":"📑 Bepul DTM test to‘plami!",
    "file_txt1":"🙋 Foyadli bo'lgan malumotlarni yuklab olish uchun botga do'stingizni taklif qilishingiz kerak. \n\n1️⃣ 3 ta do‘stingizni taklif qiling va “📓 Grant olish bo‘yicha maxsus qo‘llanma” ga ega bo'ling. \n\n2️⃣ 10 ta do‘st taklif qiling va “📑 Bepul DTM test to‘plamlaridan” dan bahramand bo'ling.",
    "invite1":"❌ Siz qo'llanmani yuklab olish uchun yana do'slaringizni taklif qilishingiz kerak.",
    "join_accep":"A'zolik tasdiqlandi.",
    "button":"🎛 Tugmalardan foydalaning.",
    "ai_txt1":"📥 Siz faylingizni muvaffaqiyatli yuklab oldingiz! \n\n🤖 Endi AI Konsultantdan ham foydalanishni xohlaysizmi?",
    "ai_txt2":"📝 Savolingizni bering!",
"ai_ask1":"👨‍💻 AI konsultant bilan suhbatlashish",
    "ai_ask":"👨‍💻 Savolingizni bering.",
    "new_ques":"🔎 Yangi savol berish"

}

ru = {
    "servis": "🗂 Какой из наших услуг вы хотели бы воспользоваться?",
    "servis_btn1": "📂 Загрузка полезной информации.",
    "servis_btn2": "🤖 Использование консультанта по AI",
    "lang_change": "⚙️ Изменить язык",
    "name_ask": "🧑🏻‍🎓 Введите свой полный F.I.O.:",
    "passport_ask": "🪪 Введите серийный номер и номер паспорта:",
    "number_ask": "Отправьте свой номер телефона с помощью кнопки Отправить номер 📞 \nили введите +998900000000 в формате: !",
    "extra_number": "📞 Ваш дополнительный номер телефона:",
    "age_ask": "🔢 Выберите свой возраст:",
    "ask_degree": "🏛 На какой этап вы подаете заявку?",
    "ask_study": "🏢 Где вы сейчас учитесь или закончили обучение?",
    "ask_region": "🏠 В каком регионе вы живете?",
    "ask_direction": "🧬 В каком направлении вы хотите учиться?",
    "ask_study_lang": "🔠 Язык обучения?",
    "ask_study_mode": "⏳ Форма обучения?",
    "ask_aplic_type": "💎 Какую возможность поступления вы ищете?",
    "ask_factor": "💼 Что для вас является наиболее важным фактором при выборе университета?",
    "ask_help": "👨‍👩‍ Кто поможет вам в поиске университета?",
    "ask_source": "🤖 Откуда вы узнали о БОТ?",
    "ask_accept": "📝 Убедитесь, что ваша информация верна:",
    "ask_right_pass": "⛓️‍💥 Вы неправильно ввели паспортные данные.\nВведите еще раз.",
    "ask_name_again": "✍️ Имя может состоять только из букв. \nПовторно введите.",
    "number_ask_again": "📲 Введите свой номер телефона правильно!",
    "ask_number_again": "🚫 Введенный вами номер не может совпадать с предыдущим!",
    "ask_sub": "🔊 Подпишитесь на канал!",
    "ask_sub1": "📝Вы хотите присоединиться к крупнейшему сообществу абитуриентов Узбекистана! \n ✅ Самая свежая информация об университетах \n ✅ Консультации по поводу стипендии и возможностей контракта \n ✅ Бесплатные ресурсы для подготовки к вступительным экзаменам \n ✅ Консультант по искусственному интеллекту 24/7",
    "ask_fill_info": "✍️ Заполнение данных!",
    "see_info": "📄 Моя информация.",
    "score": "💰 Мой счет.",
    "didnt_sub":"❌ Вы еще не являетесь участником канала!",
"ask_fill":"❌ Сначала заполните свою информацию, чтобы воспользоваться этой услугой!",
"file_button1":"🧾 Специальное руководство по получению стипендии!",
    "file_button2":"📑 Бесплатный тестовый комплект DTM!",
    "file_txt1":"🙋 Чтобы скачать полезную информацию, вам нужно пригласить друга в бот. \n\n1️⃣ Пригласите 3 друзей и получите “📓 Специальное руководство по получению гранта”. \n\n2️⃣ Пригласите 10 друзей и воспользуйтесь “📑 Бесплатными сборниками тестов DTM”.",
    "invite1":"❌ Вам нужно пригласить еще друзей, чтобы скачать руководство.",
    "join_accep":"Членство подтверждено.",
    "button":"🎛 Используйте кнопки.",
    "ai_txt1":"📥 Вы успешно скачали файл! \n\n🤖 Хотите теперь воспользоваться AI Консультантом?",
    "ai_txt2":"📝 Задайте свой вопрос!",
    "ai_ask":"👨‍💻 Задайте вопрос.",
    "ai_ask1":"👨‍💻 Поболтать с AI Консультантом.",
    "new_ques":"🔎 Задать новый вопрос"
}
