# Generated by Django 5.1.4 on 2025-03-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllUsersTgId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField()),
                ('referal_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelsToSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_id', models.IntegerField()),
                ('referred_user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudyDirections_ru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyDirections_uz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_language', models.CharField(max_length=10)),
                ('tg_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UniversityApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('passport_number', models.CharField(max_length=15, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('additional_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.CharField(choices=[('17-19', '17-19'), ('20-22', '20-22'), ('23-25', '23-25'), ('25+', '25+')], max_length=10)),
                ('education_level', models.CharField(choices=[('bachelor', 'Bakalavriat'), ('master', 'Magistratura')], max_length=10)),
                ('current_education', models.CharField(choices=[('school', 'Maktab'), ('college', 'Litsey/Kollej'), ('university', 'Universitet')], max_length=15)),
                ('region', models.CharField(max_length=100)),
                ('desired_major', models.CharField(max_length=255)),
                ('education_language', models.CharField(choices=[('uz', 'O‘zbek'), ('ru', 'Rus'), ('en', 'Ingliz')], max_length=5)),
                ('study_mode', models.CharField(choices=[('day', 'Kunduzgi'), ('evening', 'Kechki'), ('distance', 'Masofaviy'), ('external', 'Sirtqi')], max_length=10)),
                ('financial_aid', models.CharField(choices=[('grant', 'Grant'), ('contract', 'Kontrakt'), ('both', 'Ikkalasiga ham topshiraman')], max_length=10)),
                ('important_factor', models.CharField(choices=[('location', 'Joylashuv'), ('price', 'Kontrakt narxi'), ('quality', 'Ta’lim sifati'), ('grant', 'Grant imkoniyatlari'), ('diploma', 'Xalqaro diplom'), ('reputation', 'Universitet obro‘si')], max_length=20)),
                ('help_source', models.CharField(choices=[('self', 'O‘zim mustaqil qaror qilaman'), ('parents', 'Ota-onam'), ('teachers', 'Ustozlarim'), ('friends', 'Do‘stlarim')], max_length=10)),
                ('tg_id', models.IntegerField(unique=True)),
                ('bot_source', models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('search', 'Google / Yandex'), ('friend', 'Do‘stim tavsiya qildi'), ('other', 'Boshqa')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
