# Generated by Django 5.1.4 on 2025-03-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alluserstgid',
            name='tg_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_user_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='temporaryuser',
            name='tg_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='universityapplication',
            name='tg_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
