# Generated by Django 5.1.7 on 2025-03-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files_to_download',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='files_to_download',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
