# Generated by Django 5.1.4 on 2025-03-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporaryuser',
            old_name='interface_language',
            new_name='interface_lang',
        ),
    ]
