# Generated by Django 5.1.4 on 2025-03-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_alluserstgid_tg_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityapplication',
            name='additional_phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='universityapplication',
            name='age',
            field=models.CharField(choices=[('17-19', '17-19'), ('20-22', '20-22'), ('23-25', '23-25'), ('25+', '25+')], max_length=30),
        ),
        migrations.AlterField(
            model_name='universityapplication',
            name='bot_source',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('search', 'Google / Yandex'), ('friend', 'Do‘stim tavsiya qildi'), ('other', 'Boshqa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='universityapplication',
            name='current_education',
            field=models.CharField(choices=[('school', 'Maktab'), ('college', 'Litsey/Kollej'), ('university', 'Universitet')], max_length=25),
        ),
        migrations.AlterField(
            model_name='universityapplication',
            name='education_language',
            field=models.CharField(choices=[('uz', 'O‘zbek'), ('ru', 'Rus'), ('en', 'Ingliz')], max_length=30),
        ),
        migrations.AlterField(
            model_name='universityapplication',
            name='education_level',
            field=models.CharField(choices=[('bachelor', 'Bakalavriat'), ('master', 'Magistratura')], max_length=30),
        ),
        migrations.AlterField(
            model_name='universityapplication',
            name='financial_aid',
            field=models.CharField(choices=[('grant', 'Grant'), ('contract', 'Kontrakt'), ('both', 'Ikkalasiga ham topshiraman')], max_length=30),
        ),
        migrations.AlterField(
            model_name='universityapplication',
            name='help_source',
            field=models.CharField(choices=[('self', 'O‘zim mustaqil qaror qilaman'), ('parents', 'Ota-onam'), ('teachers', 'Ustozlarim'), ('friends', 'Do‘stlarim')], max_length=30),
        ),
        migrations.AlterField(
            model_name='universityapplication',
            name='important_factor',
            field=models.CharField(choices=[('location', 'Joylashuv'), ('price', 'Kontrakt narxi'), ('quality', 'Ta’lim sifati'), ('grant', 'Grant imkoniyatlari'), ('diploma', 'Xalqaro diplom'), ('reputation', 'Universitet obro‘si')], max_length=30),
        ),
        migrations.AlterField(
            model_name='universityapplication',
            name='passport_number',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='universityapplication',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='universityapplication',
            name='study_mode',
            field=models.CharField(choices=[('day', 'Kunduzgi'), ('evening', 'Kechki'), ('distance', 'Masofaviy'), ('external', 'Sirtqi')], max_length=30),
        ),
    ]
