# Generated by Django 5.1.7 on 2025-03-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_files_to_download_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityapplication',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='universityapplication',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
