# Generated by Django 5.1.4 on 2025-03-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_rename_interface_language_temporaryuser_interface_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporaryuser',
            old_name='interface_lang',
            new_name='interface_language',
        ),
    ]
