# Generated by Django 5.1.4 on 2025-03-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_rename_interface_lang_temporaryuser_interface_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelsToSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
