# Generated by Django 5.1.4 on 2025-03-06 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_universityapplication_additional_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='caption',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
