# Generated by Django 5.1.4 on 2025-03-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_channelstosubscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelstosubscribe',
            name='name',
            field=models.CharField(default='My blog chanel', max_length=100),
        ),
    ]
