# Generated by Django 5.1.4 on 2025-03-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_file_caption_alter_file_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Files_to_download',
        ),
    ]
