# Generated by Django 5.1.4 on 2024-12-14 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_installment_user_user_client_delete_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='client',
        ),
    ]
