# Generated by Django 5.1.7 on 2025-03-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_rename_file_files_to_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='QollanmaFileId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255)),
            ],
        ),
    ]
