# Generated by Django 5.1.4 on 2025-03-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_channelstosubscribe_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyDirections_ru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyDirections_uz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StudyDirections',
        ),
        migrations.AlterField(
            model_name='channelstosubscribe',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
