# Generated by Django 5.1.7 on 2025-03-07 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_qollanmafileid'),
    ]

    operations = [
        migrations.AddField(
            model_name='qollanmafileid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
