# Generated by Django 5.1.4 on 2025-03-05 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_studydirections_ru_studydirections_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred', to='bot.universityapplication')),
                ('referrer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer', to='bot.universityapplication')),
            ],
        ),
    ]
