# Generated by Django 5.1.4 on 2025-03-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referred_user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer_id',
            field=models.IntegerField(),
        ),
    ]
