# Generated by Django 5.1.4 on 2025-03-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_referral_referred_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllUsersTgId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField()),
            ],
        ),
    ]
