# Generated by Django 5.1.4 on 2025-03-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alluserstgid'),
    ]

    operations = [
        migrations.AddField(
            model_name='alluserstgid',
            name='referal_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
