# Generated by Django 5.1.4 on 2024-12-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_installment_status_alter_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'admin'), ('USER', 'user'), ('Client', 'client')], default='USER', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
