# Generated by Django 5.1.4 on 2025-03-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alluserstgid_referal_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alluserstgid',
            name='referal_count',
            field=models.IntegerField(default=0),
        ),
    ]
