# Generated by Django 5.1.4 on 2025-02-13 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_payment_payment_date_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('IELTS', 'IELTS'), ('OISD', 'OISD'), ('UNIVERSTET', 'UNIVERSTET')], max_length=255, null=True)),
                ('degree', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[("A'lo", "A'lo"), ('Yaxshi', 'Yaxshi'), ('Qoniqarli', 'Qoniqarli'), ('Qoniqarsiz', 'Qoniqarsiz')], max_length=255, null=True)),
                ('ball', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='installment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='installment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Sms',
        ),
        migrations.AddField(
            model_name='user',
            name='ball',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bonus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'admin'), ('USER', 'user'), ('EMPLOYEE', 'Employee')], default='USER', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user'),
        ),
        migrations.AddField(
            model_name='certification',
            name='files',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='bot.file'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Installment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
