# Generated by Django 5.1.4 on 2025-02-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_certification_file_kpi_remove_installment_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='type',
            field=models.CharField(blank=True, choices=[('GOETHE', 'Goethe'), ('MILLIY', 'Milliy'), ('TELC', 'Telc'), ('ÖSD', 'ÖSD'), ('Test_DAF', 'Test DAF'), ('prach_Diplom', 'Prache Diplom')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('USER', 'Foydalanuvchi'), ('EMPLOYEE', 'Xodim')], default='USER', max_length=255, null=True),
        ),
    ]
