# Generated by Django 5.1.4 on 2025-02-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_alter_certification_type_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certifications',
            field=models.ManyToManyField(blank=True, related_name='user_certifications', to='bot.certification'),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, choices=[('1', '1 yil'), ('2', '2 yil'), ('3', '3 yil'), ('4', '4 yil'), ('5', '5 yil'), ('PROFESSIONAL', 'Professional')], default='1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos'),
            preserve_default=False,
        ),
    ]
