# Generated by Django 5.1.4 on 2025-02-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_user_certifications_user_experience_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='degree',
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
