# Generated by Django 5.1.4 on 2025-02-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_remove_user_degree_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='files',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
