# Generated by Django 5.1.4 on 2025-02-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_alter_certification_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bosh_ustoz', models.FloatField(default=0, max_length=255)),
                ('Ustoz', models.FloatField(default=0, max_length=255)),
                ('Yordamchi_ustoz', models.FloatField(default=0, max_length=255)),
                ('Stajior', models.FloatField(default=0, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='certification',
            name='owner',
            field=models.CharField(blank=True, choices=[('ME', 'Shaxsiy'), ('Student', "O'quvchimning")], default='ME', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='status',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'Tasdiqlandi'), ('IN_PROGRESS', 'Jarayonda'), ('REJECTED', 'Bekor qilindi')], default='IN_PROGRESS', max_length=255, null=True),
        ),
    ]
