# Generated by Django 5.1.4 on 2025-03-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_remove_user_certifications_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('passport_number', models.CharField(max_length=15, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('additional_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.CharField(choices=[('17-19', '17-19'), ('20-22', '20-22'), ('23-25', '23-25'), ('25+', '25+')], max_length=10)),
                ('education_level', models.CharField(choices=[('bachelor', 'Bakalavriat'), ('master', 'Magistratura')], max_length=10)),
                ('current_education', models.CharField(choices=[('school', 'Maktab'), ('college', 'Litsey/Kollej'), ('university', 'Universitet')], max_length=15)),
                ('region', models.CharField(max_length=100)),
                ('desired_major', models.CharField(max_length=255)),
                ('education_language', models.CharField(choices=[('uz', 'O‘zbek'), ('ru', 'Rus'), ('en', 'Ingliz')], max_length=5)),
                ('study_mode', models.CharField(choices=[('day', 'Kunduzgi'), ('evening', 'Kechki'), ('distance', 'Masofaviy'), ('external', 'Sirtqi')], max_length=10)),
                ('financial_aid', models.CharField(choices=[('grant', 'Grant'), ('contract', 'Kontrakt'), ('both', 'Ikkalasiga ham topshiraman')], max_length=10)),
                ('important_factor', models.CharField(choices=[('location', 'Joylashuv'), ('price', 'Kontrakt narxi'), ('quality', 'Ta’lim sifati'), ('grant', 'Grant imkoniyatlari'), ('diploma', 'Xalqaro diplom'), ('reputation', 'Universitet obro‘si')], max_length=20)),
                ('help_source', models.CharField(choices=[('self', 'O‘zim mustaqil qaror qilaman'), ('parents', 'Ota-onam'), ('teachers', 'Ustozlarim'), ('friends', 'Do‘stlarim')], max_length=10)),
                ('interface_language', models.CharField(max_length=10)),
                ('tg_id', models.IntegerField()),
                ('bot_source', models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('search', 'Google / Yandex'), ('friend', 'Do‘stim tavsiya qildi'), ('other', 'Boshqa')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bonus',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Kpi',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
