# Generated by Django 5.1.4 on 2025-03-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_universityapplication_delete_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_language', models.CharField(max_length=10)),
                ('tg_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='universityapplication',
            name='interface_language',
        ),
        migrations.RemoveField(
            model_name='universityapplication',
            name='tg_id',
        ),
    ]
