# Generated by Django 5.1.4 on 2025-03-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_temporaryuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityapplication',
            name='tg_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
